ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS kyc_status TEXT NOT NULL DEFAULT 'pending';

ALTER TABLE users
  ALTER COLUMN gov_id_front_url DROP NOT NULL,
  ALTER COLUMN gov_id_back_url DROP NOT NULL;
